---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-12-30 - 04:15:12 +0000
  labels:
    app.kubernetes.io/name: quarkus-investiment
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-investiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-investiment
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-12-30 - 04:15:12 +0000
      labels:
        app.kubernetes.io/name: quarkus-investiment
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: jneris/quarkus-investiment:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: quarkus-investiment
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-12-30 - 04:15:12 +0000
  labels:
    app.kubernetes.io/name: quarkus-investiment
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-investiment
spec:
  ports:
    - name: http
      nodePort: 31974
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-investiment
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
